-- -------------------------- LIBRARY PROJECT --------------------------------

-- CREATING DATABASE 

CREATE DATABASE LIBRARY ;

USE LIBRARY ;

-- CREATING TABLES

CREATE TABLE LIBRARY_BRANCH 
(LIBRARY_BRANCH_BRANCHID INT PRIMARY KEY AUTO_INCREMENT ,
LIBRARY_BRANCH_BRANCHNAME VARCHAR (50) ,
LIBREARY_BRANCH_BRANCHADDRESS VARCHAR (50) ); 



CREATE TABLE PUBLISHER 
(PUBLISHER_PUBLISHERNAME VARCHAR (100) PRIMARY KEY ,
PUBLISHER_PUBLISHERADDRESS VARCHAR(250) ,
PUBLISHER_PUBLISHERPHONE VARCHAR(50) ) ;

CREATE TABLE BORROWER
(BORROWER_CARDNO INT PRIMARY KEY ,
BORROWER_BORROWERNAME VARCHAR (50) ,
BORROWER_BORROWERADDRESS VARCHAR (50) ,
BORROWER_BORROWERPHONE varchar(50) );


CREATE TABLE BOOKS
(BOOK_BOOKID INT PRIMARY KEY ,
BOOK_TITLE varchar (100) ,
BOOK_PUBLISHERNAME VARCHAR(100) ,
FOREIGN KEY (BOOK_PUBLISHERNAME) REFERENCES  PUBLISHER(PUBLISHER_PUBLISHERNAME) on delete cascade ) ;


CREATE TABLE BOOK_AUTHORS
(BOOK_AUTHORS_AUTHORID INT PRIMARY KEY AUTO_INCREMENT ,
BOOK_AUTHORS_BOOKID INT ,
BOOK_AUTHORS_AUTHORNAME VARCHAR(50) ,
FOREIGN KEY (BOOK_AUTHORS_BOOKID)  REFERENCES BOOKS(BOOK_BOOKID) ON DELETE CASCADE ) ;


CREATE TABLE BOOK_COPIES
(BOOK_COPIES_COPIESID INT PRIMARY KEY AUTO_INCREMENT ,
BOOK_COPIES_BOOKID INT,
BOOK_COPIES_BRANCHID INT,
BOOK_COPIES_NO_OF_COPIES INT ,
FOREIGN KEY (BOOK_COPIES_BOOKID) REFERENCES BOOKS(BOOK_BOOKID) ON DELETE CASCADE ,
FOREIGN KEY (BOOK_COPIES_BRANCHID) REFERENCES LIBRARY_BRANCH(LIBRARY_BRANCH_BRANCHID) ON DELETE CASCADE ) ;



CREATE TABLE BOOK_LOANS
(BOOK_LOANS_LOANAID INT PRIMARY KEY AUTO_INCREMENT ,
BOOK_LOANS_BOOKID INT ,
BOOK_LOANS_BRANCHID INT ,
BOOK_LOANS_CARDNO INT ,
BOOK_LOANS_DATEOUT VARCHAR(20) ,
BOOK_LOANS_DUEDATE VARCHAR(20),
FOREIGN KEY (BOOK_LOANS_BOOKID) REFERENCES BOOKS(BOOK_BOOKID) ON DELETE CASCADE ,
FOREIGN KEY (BOOK_LOANS_BRANCHID) REFERENCES LIBRARY_BRANCH(LIBRARY_BRANCH_BRANCHID) ON DELETE CASCADE ,
FOREIGN KEY (BOOK_LOANS_CARDNO) REFERENCES BORROWER(BORROWER_CARDNO) ON DELETE CASCADE) ;



SELECT * FROM LIBRARY_BRANCH ;
SELECT * FROM BORROWER;
SELECT * FROM  PUBLISHER;
SELECT * FROM BOOKS;
SELECT * FROM BOOK_AUTHORS;
SELECT * FROM BOOK_COPIES;
SELECT * FROM BOOK_LOANS;




-- QNA

-- 1. How many copies of the book titled "The Lost Tribe" are owned by the library branch whose name is "Sharpstown"?

SELECT LB.LIBRARY_BRANCH_BRANCHID,LB.LIBRARY_BRANCH_BRANCHNAME,B.BOOK_TITLE ,BC.BOOK_COPIES_NO_OF_COPIES 
FROM LIBRARY_BRANCH AS LB
JOIN BOOK_COPIES AS BC
ON LB.LIBRARY_BRANCH_BRANCHID = BC.BOOK_COPIES_BRANCHID 
JOIN BOOKS AS B
ON BC.BOOK_COPIES_BOOKID = B.BOOK_BOOKID 
WHERE LB.LIBRARY_BRANCH_BRANCHNAME = "SHARPSTOWN" AND B.BOOK_TITLE = "THE LOST TRIBE" ;

 
-- 2. How many copies of the book titled "The Lost Tribe" are owned by each library branch?
 

SELECT  B.BOOK_BOOKID,B.BOOK_TITLE,LB.LIBRARY_BRANCH_BRANCHNAME,(BC.BOOK_COPIES_NO_OF_COPIES) AS COPIES_OWNED
 FROM BOOKS AS B
 JOIN BOOK_COPIES AS BC
 ON B.BOOK_BOOKID = BC.BOOK_COPIES_BOOKID 
 JOIN LIBRARY_BRANCH AS LB
 ON BC.BOOK_COPIES_BRANCHID =  LB.LIBRARY_BRANCH_BRANCHID 
 WHERE B.BOOK_TITLE = "THE LOST TRIBE";
 

-- 3. Retrieve the names of all borrowers who do not have any books checked out.

SELECT * FROM BORROWER
WHERE BORROWER_CARDNO NOT IN(SELECT BOOK_LOANS_CARDNO FROM BOOK_LOANS) ;

-- 4. For each book that is loaned out from the "Sharpstown" branch and whose DueDate is 2/3/18, retrieve the book title, the borrower's name, and the borrower's address. 


SELECT B.BORROWER_BORROWERNAME,B.BORROWER_BORROWERADDRESS,B.BORROWER_BORROWERPHONE,BO.BOOK_TITLE,BL.BOOK_LOANS_DUEDATE,
LB.LIBRARY_BRANCH_BRANCHNAME 
FROM BORROWER AS B
JOIN BOOK_LOANS AS BL
ON B.BORROWER_CARDNO = BL.BOOK_LOANS_CARDNO
JOIN BOOKS AS BO 
ON BO.BOOK_BOOKID = BL.BOOK_LOANS_BOOKID 
JOIN LIBRARY_BRANCH AS LB
ON LB.LIBRARY_BRANCH_BRANCHID = BL.BOOK_LOANS_BRANCHID
WHERE LB.LIBRARY_BRANCH_BRANCHNAME = "SHARPSTOWN" AND BL.BOOK_LOANS_DUEDATE = '2/3/18' ; 



-- 5. For each library branch, retrieve the branch name and the total number of books loaned out from that branch.

SELECT LB.LIBRARY_BRANCH_BRANCHNAME,LB.LIBREARY_BRANCH_BRANCHADDRESS, COUNT(BL.BOOK_LOANS_DATEOUT) AS BOOK_COUNT
FROM LIBRARY_BRANCH AS LB 
JOIN BOOK_LOANS AS BL
ON LB.LIBRARY_BRANCH_BRANCHID = BL.BOOK_LOANS_BRANCHID
GROUP BY  LB.LIBRARY_BRANCH_BRANCHNAME,LB.LIBREARY_BRANCH_BRANCHADDRESS ;




-- 6.Retrieve the names, addresses, and number of books checked out for all borrowers who have more than five books checked out.
 

SELECT B.BORROWER_BORROWERNAME,B.BORROWER_BORROWERADDRESS , B.BORROWER_BORROWERPHONE , COUNT(BL.BOOK_LOANS_BOOKID) AS BOOK_COUNT
FROM BORROWER AS B
JOIN BOOK_LOANS AS BL
ON  B.BORROWER_CARDNO = BL.BOOK_LOANS_CARDNO
GROUP BY B.BORROWER_BORROWERNAME,B.BORROWER_BORROWERADDRESS , B.BORROWER_BORROWERPHONE 
HAVING (BOOK_COUNT > 5);



-- ---------------



-- 7. For each book authored by "Stephen King", retrieve the title and the number of copies owned by the library branch whose name is "Central".

SELECT BA.BOOK_AUTHORS_BOOKID , BA.BOOK_AUTHORS_AUTHORNAME , B.BOOK_TITLE , LB.LIBRARY_BRANCH_BRANCHNAME ,BC.BOOK_COPIES_NO_OF_COPIES
FROM BOOK_AUTHORS AS BA
JOIN BOOKS AS B
ON  BA.BOOK_AUTHORS_BOOKID = B.BOOK_BOOKID 
JOIN BOOK_COPIES AS BC
ON B.BOOK_BOOKID = BC.BOOK_COPIES_BOOKID 
JOIN LIBRARY_BRANCH AS LB
ON BC.BOOK_COPIES_BRANCHID = LB.LIBRARY_BRANCH_BRANCHID
WHERE BA.BOOK_AUTHORS_AUTHORNAME = "STEPHEN KING" AND LB.LIBRARY_BRANCH_BRANCHNAME = "CENTRAL";









